---
# tasks file for gromacs
- name: Create /nfs/scratch/gromacs
  become: true
  file:
    path: "/nfs/scratch/gromacs"
    state: directory
    owner: opc
    mode: 0770
    group: opc
    recurse: yes
    
- name: download gromacs binaries
  get_url: 
    url: "{{gromacs_binaries}}"  
    dest: "/nfs/scratch/gromacs"
    mode: 0770

- name: untar gromacs binaries
  unarchive: 
    src: "{{ item }}" 
    dest: "/nfs/scratch/gromacs" 
  with_fileglob:
    - "/nfs/scratch/gromacs/*"

- name: change permissions on gromacs folder
  become: true 
  shell: "chmod +x /nfs/scratch/gromacs/*"
 
# Post Installation 

- name: make models directory
  ansible.builtin.file:
    path: "/nfs/scratch/work"
    state: directory
    recurse: yes
    owner: opc
    group: opc
    mode: '0777'

- name: download model 
  get_url: 
    url: "{{gromacs_model}}"
    dest: "/nfs/scratch/work"
    mode: '0777' 

  # visualization

- name: Create /nfs/scratch/vmd
  become: true
  file:
    path: "/nfs/scratch/vmd"
    state: directory
    owner: opc
    mode: 0770
    group: opc
    recurse: yes

- name: Download VMD
  get_url: 
    url: "https://objectstorage.us-phoenix-1.oraclecloud.com/p/bpR0VM0GaNlc4yQsGLwO4lZwneKxXwN8vUdtyKcVZcE/n/hpc/b/HPC_APPS/o/vmd-1.9.3.bin.LINUXAMD64-CUDA8-OptiX4-OSPRay111p1.opengl.tar.gz"
    dest: "/nfs/scratch/vmd"
    mode: '0777' 

- name: untar VMD folder
  unarchive: 
    src: "{{ item }}" 
    dest: "/nfs/scratch/vmd" 
  with_fileglob:
    - "/nfs/scratch/vmd/*"

- name: install VMD 
  shell: |
    cd /nfs/scratch/vmd/vmd-1.9.3
    ./configure
    cd src
    sudo make install


- name: change permissions on vmd-1.9.3 folder
  become: true 
  shell: "chmod +x /nfs/scratch/vmd/vmd-1.9.3/*"
  
- name: set up VNC
  become: true
  shell: |
    sudo yum -y groupinstall 'Server with GUI'
    sudo yum -y install tigervnc-server mesa-libGL
    sudo systemctl set-default graphical.target
    sudo cp /usr/lib/systemd/system/vncserver@.service /etc/systemd/system/vncserver@:1.service
    sudo sed -i 's/<USER>/opc/g' /etc/systemd/system/vncserver@:1.service
    sudo mkdir /home/opc/.vnc/
    sudo chown opc:opc /home/opc/.vnc
    echo 'Hpc123!' | vncpasswd -f > /home/opc/.vnc/passwd
    chown opc:opc /home/opc/.vnc/passwd
    chmod 600 /home/opc/.vnc/passwd
    sudo systemctl start vncserver@:1.service
    sudo systemctl enable vncserver@:1.service

- name: update bashrc
  blockinfile:
    dest: "/home/opc/.bashrc"
    block: |
      source /nfs/scratch/gromacs/binaries/bin/GMXRC
      export PATH=/nfs/scratch/gromacs/binaries/bin/:$PATH
      export PATH=/nfs/scratch/work/:$PATH
      export PATH=/nfs/scratch/vmd/vmd-1.9.3/:$PATH
    # marker: '# {mark} ANSIBLE MANAGED BLOCK - virtualenv'
    insertbefore: EOF
    create: yes 



