---
# tasks file for gromacs
- name: Create /nfs/scratch/gromacs
  become: true
  file:
    path: "/nfs/scratch/gromacs"
    state: directory
    owner: opc
    mode: 0770
    group: opc
    recurse: yes
    
- name: download gromacs binaries
  get_url: 
    url: "{{gromacs_binaries}}"  
    dest: "/nfs/scratch/gromacs"
    mode: 0770

- name: untar gromacs binaries
  unarchive: 
    src: "{{ item }}" 
    dest: "/nfs/scratch/gromacs" 
  with_fileglob:
    - "/nfs/scratch/gromacs/*"

- name: change permissions on gromacs folder
  become: true 
  shell: "chmod +x /nfs/scratch/gromacs/*"
 
# Post Installation 

- name: make models directory
  ansible.builtin.file:
    path: "/nfs/scratch/work"
    state: directory
    recurse: yes
    owner: opc
    group: opc
    mode: '0777'

- name: download model 
  get_url: 
    url: "{{gromacs_model}}"
    dest: "/nfs/scratch/work"
    mode: '0777' 

  # visualization

- name: Create /nfs/scratch/vmd
  become: true
  file:
    path: "/nfs/scratch/vmd"
    state: directory
    owner: opc
    mode: 0770
    group: opc
    recurse: yes

- name: Download VMD
  get_url: 
    url: "https://objectstorage.us-phoenix-1.oraclecloud.com/p/bpR0VM0GaNlc4yQsGLwO4lZwneKxXwN8vUdtyKcVZcE/n/hpc/b/HPC_APPS/o/vmd-1.9.3.bin.LINUXAMD64-CUDA8-OptiX4-OSPRay111p1.opengl.tar.gz"
    dest: "/nfs/scratch/vmd"
    mode: '0777' 

- name: untar VMD folder
  unarchive: 
    src: "{{ item }}" 
    dest: "/nfs/scratch/vmd" 
  with_fileglob:
    - "/nfs/scratch/vmd/*"

- name: change permissions on vmd-1.9.3 folder
  become: true 
  shell: "chmod +x /nfs/scratch/vmd/vmd-1.9.3/*"

- name: update bashrc
  blockinfile:
    dest: "/home/opc/.bashrc"
    block: |
      source /nfs/scratch/gromacs/binaries/bin/GMXRC
      export PATH=/nfs/scratch/gromacs/binaries/bin/:$PATH
      export PATH=/nfs/scratch/work/:$PATH
      export PATH=/nfs/scratch/vmd/vmd-1.9.3/:$PATH
    # marker: '# {mark} ANSIBLE MANAGED BLOCK - virtualenv'
    insertbefore: EOF
    create: yes 



